name: Integrate

on:
  pull_request:
    branches: ["main", "dev"]
  push:
    branches: ["dev"]
  workflow_dispatch:

jobs:
  Tests:
    name: Build and Integration Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Set up JDK
        uses: actions/setup-java@v1
        with:
        java-version: '17'

      - name: Build and Test
        run: mvn clean install

